#!/bin/bash

# test-cli: A test harness for RoleSpec
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>

# Select proper test suite according to distro Falling back to detecting yum
# because base centos doesn't have lsb_release installed...
if [[ -r /usr/bin/yum ]]; then
  DISTRIBUTION=centos
elif [[ -r /usr/sbin/pacman ]]; then
  DISTRIBUTION=arch
else
  DISTRIBUTION=debian
fi

if [[ ! -r tests/test-helper-$DISTRIBUTION ]]; then
  echo "No tests suite for this distribution."
  echo "Please consider creating tests/test-helper-DISTRIBUTIONNAME"
  exit 1
fi
  
. tests/test-helper-${DISTRIBUTION}
. tests/test-suite

# Execute tests
setup_test

set -e
ROLESPEC_TEST_SELF=true TRAVIS_REPO_SLUG="" TRAVIS_BUILD_DIR="" bash bin/rolespec -r "${ROLESPEC_TEST_SELF_ROLE}"

teardown_test
