#!/bin/bash

# config: Configuration settings for the RoleSpec script
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org


# ---- Functions ----

guess_distribution() {
  if [[ -r /usr/bin/yum ]]; then
  echo centos
elif [[ -r /usr/sbin/pacman ]]; then
  echo arch
else
  echo debian
fi
}

find_up () {
  # Traverse backwards appending ../ to the path until we find a RoleSpec
  # working directory or hit the root of the file system
  local slashes="${PWD//[^\/]/}"
  local directory="${PWD}"

  for (( n="${#slashes}"; n>0; --n )) ; do
    [[ -d "${directory}/tests" && -d "${directory}/roles" ]] && \
      echo "${directory}" && return
    directory="$directory/.."
  done
}


# ---- Configuration ----

# Information
ROLESPEC_RELEASE_NAME="$(lsb_release -a 2>/dev/null | grep Codename | awk '{print $2}')"
ROLESPEC_DISTRIBUTION_NAME=$(guess_distribution)
ROLESPEC_FQDN="$(hostname -f)"

# Load the VERSION file from the correct path
if [[ -f "${ROLESPEC_LIB}/VERSION" ]]; then
  ROLESPEC_VERSION="$(cat "${ROLESPEC_LIB}/VERSION")"
else
  ROLESPEC_VERSION="$(cat "VERSION")"
fi

# Default environment variables
ROLESPEC_TEST_SELF="${ROLESPEC_TEST_SELF}"

# Set the runtime path based on what env RoleSpec is being ran under
if [[ -n "${ROLESPEC_TEST_SELF}" ]]; then
  ROLESPEC_RUNTIME="/tmp/rolespec/test_self"
elif [[ -n "${ROLESPEC_TRAVIS}" ]]; then
  ROLESPEC_RUNTIME="$(pwd)"
else
  ROLESPEC_RUNTIME="$(find_up)"
fi
echo "################# ROLESPEC_RUNTIME=${ROLESPEC_RUNTIME}"

# Working paths
ROLESPEC_ROLES="${ROLESPEC_RUNTIME}/roles"
ROLESPEC_TESTS="${ROLESPEC_RUNTIME}/tests"
ROLESPEC_TRAVIS_TESTS="${ROLESPEC_RUNTIME}/travis/tests"

# Test paths
ROLESPEC_HOSTS="inventory/hosts"
ROLESPEC_META="meta/main.yml"
ROLESPEC_PLAYBOOK="playbooks/test.yml"

# Ansible configuration
ROLESPEC_ANSIBLE_SOURCE="https://github.com/ansible/ansible"
ROLESPEC_ANSIBLE_INSTALL="/tmp/ansible"
ROLESPEC_ANSIBLE_CONFIG="$(pwd)/ansible.cfg"
ROLESPEC_ANSIBLE_ROLES="${ROLESPEC_ROLES}${ROLESPEC_TRAVIS_ROLES_PATH}"

# Test DSL helpers
if [[ -r "${ROLESPEC_LIB}/config-${ROLESPEC_DISTRIBUTION_NAME}" ]]; then
  . "${ROLESPEC_LIB}/config-${ROLESPEC_DISTRIBUTION_NAME}"
fi
