#!/bin/bash

# init: Init a new working directory for RoleSpec
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>

realpath() {
    python -c "import os; print(os.path.realpath('$1'))"
}


init() {
	local path=$(realpath "${1}")

	if [[ -d ${path} ]]; then
		error "Path already exists: ${path}"
	fi

	mkdir -p "${path}/tests"
	mkdir -p "${path}/roles"

	[ ! -e "${path}/.rolespec.cfg" ] && cat > "${path}/.rolespec.cfg" <<EOF
# You custom configuration should only apply when not running in travis
if [[ -z "\${ROLESPEC_TRAVIS}" ]]; then
    # Put your configuration here
    # Example:
    # ROLESPEC_ANSIBLE_ROLES="\${ROLESPEC_ANSIBLE_ROLES}:/path/to/my/roles"
fi
EOF
	echo "Initialized new RoleSpec directory in ${path}"
}
