#!/bin/bash

# ui: Colored log outputs
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org


# Colored log output
log() {
  local bold="${3:-}"
  printf "\033[${bold};${1}m${2}\033[0m"
}

info() {
  log "36" "${1}" "${2}"
}

warn() {
  log "33" "${1}" "${2}"
}

error() {
  echo -e "${1}"
  exit 1
}

notify() {
  log "35" "${1}" "${2}"
}

test_pass() {
  log "32" "${1}" "${2}"
  echo
}

test_fail() {
  log "31" "${1}" "${2}"
}

# Output helpers
label() {
  echo
  echo "$(notify "${1}" "${3}"): [$(info "${2}")]"
}

ansible_run() {
  label "TEST" "${1}" 1
}

rolespec_run() {
  echo -e "\nROLESPEC: [${1}]\n"
}

validate_error() {
  printf "%s [%s] %s\n" \
    "${3}" \
    "$(test_fail ${2})" \
    "${1}"
  exit 1
}

validate_warn() {
  printf "%s [%s] %s\n" \
    "${3}" \
    "$(warn ${2})" \
    "${1}"
}
